[project]
name = "c-shipgen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "hull_parameterization",
    "matplotlib>=3.10.3",
    "numpy>=2.2.5",
    "pymoo>=0.6.1.3",
    "scikit-learn>=1.6.1",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
]

[tool.uv]
dev-dependencies = [
    "ipykernel>=6.29.5",
]
package = true

[tool.uv.sources]
hull_parameterization = { path = "../hull_parameterization", editable = true }
